name: Generate Go Code from Proto

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Clone proto repo
        run: git clone https://github.com/Aidana2007/ad-proto.git /tmp/protos

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Install plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate code
        run: |
          protoc -I=/tmp/protos \
            --go_out=paths=source_relative:. \
            --go-grpc_out=paths=source_relative:. \
            /tmp/protos/order/v1/order.proto \
            /tmp/protos/payment/v1/payment.proto

      - name: Cleanup unwanted folders
        run: |
          rm -rf protos || true
          rm -rf github.com || true
          rm -rf .github/Aidana2007 || true

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "auto: generate pb.go"
            git push
          else
            echo "No changes to commit"
          fi